export const SocketEvents = {
  MessageNew: 'message:new',
  MessageEdited: 'message:edited',
  MessageDeleted: 'message:deleted',
  MessageSeen: 'message:seen',
  MessagePinned: 'message:pinned',
  MessageUnpinned: 'message:unpinned',
  MessageMentioned: 'message:mentioned',
  ReactionAdded: 'reaction:added',
  ReactionRemoved: 'reaction:removed',
  ThreadReply: 'thread:reply',
  MessagePreviewAttached: 'message:preview-attached',
  TypingStart: 'typing:start',
  TypingStop: 'typing:stop',
  PresenceOnline: 'presence:online',
  PresenceOffline: 'presence:offline',
  FriendRequestReceived: 'friend:request-received',
  FriendRequestAccepted: 'friend:request-accepted',
  FriendRequestRejected: 'friend:request-rejected',
  FriendRequestCancelled: 'friend:request-cancelled',
  FriendRemoved: 'friend:removed',
  PrivacyUpdated: 'privacy:updated',
  ChatRequestReceived: 'chat:request-received',
  ChatRequestAccepted: 'chat:request-accepted',
  ChatRequestRejected: 'chat:request-rejected',
  ChatStatusChanged: 'chat:status-changed',
};
